-- Migration inicial para substituir a planilha PARADA U-700 ATUAL.xlsx.
-- As colunas foram mantidas com os mesmos nomes dos cabecalhos do Excel para
-- permitir uma importacao 1:1 nesta primeira etapa da refatoracao.

create table if not exists public.parada_u700_operacoes (
  id bigint generated by default as identity primary key,
  row_number integer not null,
  "Ordem" text not null,
  "Operação" text not null default '',
  "Suboperação" text not null default '',
  "Campo seleção" text not null default '',
  "Centro trabalho" text not null default '',
  "TxtDesc.Oper." text not null default '',
  "TEXTO" text not null default '',
  "QUENTE/FRIO" text not null default '',
  "APOIO" text not null default '',
  "VERMELHA     AMARELA    BRANCA" text not null default '',
  "Status sistema" text not null default '',
  "Status usuário" text not null default '',
  "Trabalho" numeric(12, 3) not null default 0,
  "Trabalho real" numeric(12, 3) not null default 0,
  "Duração normal" numeric(12, 3) not null default 0,
  "Fim execução" text not null default '',
  "Restr.início" text not null default '',
  "Restriç.início" text not null default '',
  "Fase parada" text not null default '',
  "Critério fase" text not null default '',
  "Status app" text not null default 'Pendente',
  "Observação app" text not null default '',
  "Atualizado em" text not null default '',
  "Atualizado por" text not null default '',
  "Atualizado por id" text not null default '',
  "Versão app" text not null default '',
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint parada_u700_operacoes_status_app_check
    check ("Status app" in ('Pendente', 'Andamento', 'Concluida', 'Concluída')),
  constraint parada_u700_operacoes_unique_operation
    unique ("Ordem", "Operação", "Suboperação")
);

create table if not exists public.parada_u700_anexos (
  id uuid primary key default gen_random_uuid(),
  "Id" text not null unique,
  "Ordem" text not null default '',
  "Nome arquivo" text not null default '',
  "Caminho relativo" text not null default '',
  "Tipo" text not null default '',
  "Tamanho" bigint not null default 0,
  "Criado em" text not null default '',
  "Excluído em" text not null default '',
  "Criado por" text not null default '',
  "Criado por id" text not null default '',
  "Excluído por" text not null default '',
  "Excluído por id" text not null default '',
  "Versão app" text not null default '',
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.parada_u700_status_history (
  id bigint generated by default as identity primary key,
  ordem text not null,
  operacao text not null default '',
  suboperacao text not null default '',
  previous_status text,
  next_status text not null,
  previous_observation text,
  next_observation text,
  changed_by text not null default '',
  changed_by_id text not null default '',
  changed_at timestamptz not null default now()
);

create index if not exists parada_u700_operacoes_ordem_idx
  on public.parada_u700_operacoes ("Ordem");

create index if not exists parada_u700_operacoes_equipamento_idx
  on public.parada_u700_operacoes ("Campo seleção");

create index if not exists parada_u700_operacoes_fase_idx
  on public.parada_u700_operacoes ("Fase parada");

create index if not exists parada_u700_operacoes_status_app_idx
  on public.parada_u700_operacoes ("Status app");

create index if not exists parada_u700_anexos_ordem_idx
  on public.parada_u700_anexos ("Ordem");

create or replace function public.parada_u700_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists parada_u700_operacoes_touch_updated_at on public.parada_u700_operacoes;
create trigger parada_u700_operacoes_touch_updated_at
before update on public.parada_u700_operacoes
for each row
execute function public.parada_u700_touch_updated_at();

drop trigger if exists parada_u700_anexos_touch_updated_at on public.parada_u700_anexos;
create trigger parada_u700_anexos_touch_updated_at
before update on public.parada_u700_anexos
for each row
execute function public.parada_u700_touch_updated_at();

create or replace function public.parada_u700_log_status_update()
returns trigger
language plpgsql
as $$
begin
  if old."Status app" is distinct from new."Status app"
     or old."Observação app" is distinct from new."Observação app" then
    insert into public.parada_u700_status_history (
      ordem,
      operacao,
      suboperacao,
      previous_status,
      next_status,
      previous_observation,
      next_observation,
      changed_by,
      changed_by_id
    )
    values (
      new."Ordem",
      new."Operação",
      new."Suboperação",
      old."Status app",
      new."Status app",
      old."Observação app",
      new."Observação app",
      new."Atualizado por",
      new."Atualizado por id"
    );
  end if;

  return new;
end;
$$;

drop trigger if exists parada_u700_operacoes_log_status_update on public.parada_u700_operacoes;
create trigger parada_u700_operacoes_log_status_update
after update of "Status app", "Observação app" on public.parada_u700_operacoes
for each row
execute function public.parada_u700_log_status_update();

-- Views com nomes ergonomicos para consultas futuras, preservando as tabelas
-- brutas com os cabecalhos identicos ao Excel.
create or replace view public.parada_u700_operacoes_view as
select
  id,
  row_number,
  "Ordem" as ordem,
  "Operação" as operacao,
  "Suboperação" as suboperacao,
  "Campo seleção" as campo_selecao,
  "Centro trabalho" as centro_trabalho,
  "TxtDesc.Oper." as descricao,
  "TEXTO" as texto,
  "QUENTE/FRIO" as quente_frio,
  "APOIO" as apoio,
  "VERMELHA     AMARELA    BRANCA" as pt_colorida,
  "Status sistema" as status_sistema,
  "Status usuário" as status_usuario,
  "Trabalho" as trabalho,
  "Trabalho real" as trabalho_real,
  "Duração normal" as duracao_normal,
  "Fim execução" as fim_execucao,
  "Restr.início" as restr_inicio,
  "Restriç.início" as restric_inicio,
  "Fase parada" as fase_parada,
  "Critério fase" as criterio_fase,
  "Status app" as status_app,
  "Observação app" as observacao_app,
  "Atualizado em" as atualizado_em,
  "Atualizado por" as atualizado_por,
  "Atualizado por id" as atualizado_por_id,
  "Versão app" as versao_app,
  inserted_at,
  updated_at
from public.parada_u700_operacoes;

create or replace view public.parada_u700_anexos_view as
select
  id,
  "Id" as excel_id,
  "Ordem" as ordem,
  "Nome arquivo" as nome_arquivo,
  "Caminho relativo" as caminho_relativo,
  "Tipo" as tipo,
  "Tamanho" as tamanho,
  "Criado em" as criado_em,
  "Excluído em" as excluido_em,
  "Criado por" as criado_por,
  "Criado por id" as criado_por_id,
  "Excluído por" as excluido_por,
  "Excluído por id" as excluido_por_id,
  "Versão app" as versao_app,
  inserted_at,
  updated_at
from public.parada_u700_anexos;

grant select, insert, update, delete on public.parada_u700_operacoes to anon, authenticated;
grant select, insert, update, delete on public.parada_u700_anexos to anon, authenticated;
grant select on public.parada_u700_operacoes_view to anon, authenticated;
grant select on public.parada_u700_anexos_view to anon, authenticated;
grant select on public.parada_u700_status_history to anon, authenticated;
